parameters:
    hike_manager.class: AppBundle\Manager\HikeManager
    contact_manager.class: AppBundle\Manager\ContactManager

services:
    app_user.profile.form.type:
        class: AppBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }
    app_user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
    hike.manager:
        class:     "%hike_manager.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    contact.manager:
        class:     "%contact_manager.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        